%write to file


writelines([append('M11=',taustr{1}(1),';'),...
    append('M12=',taustr{1}(2),';'),append('M21=',taustr{2}(1),';'),...
    append('M22=',taustr{2}(2),';'),...
    append('V1=',taustr{1}(3),';'),...
    append('V2=',taustr{2}(4),';'),...
    append('G1=',' 0 ',';'),...
    append('G2=',taustr{2}(3),';'),...
    'M = [M11 M12; M21 M22];',...
    'qdd = M\(tau-[V1;V2]-[G1;G2]*g -D)'],text_out)